app:
  catdb:
    datasource:
      class-driver: com.mysql.cj.jdbc.Driver
      username: root
      password: 55555
      url: jdbc:mysql://localhost:3306/cats
  dogdb:
    datasource:
      class-driver: com.mysql.cj.jdbc.Driver
      username: root
      password: 55555
      url: jdbc:mysql://localhost:3306/dogs